# Generated by Django 4.2.4 on 2023-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
