# Generated by Django 4.2.4 on 2023-08-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='probation',
            field=models.IntegerField(),
        ),
    ]
